services:
  nim-llama-8b:
    image: nvcr.io/nim/meta/llama3-8b-instruct:1.0.0
    shm_size: 35gb
    runtime: nvidia
    hostname: nim-llama-8b
    healthcheck:
      test: python /healthcheck.py
      interval: 1m
      timeout: 30s
      retries: 15
      start_period: 30s
    environment:
      - NGC_API_KEY=${NGC_API_KEY}
      - NIM_MODEL_PROFILE=vllm-fp16-tp2
      - NIM_MANIFEST_ALLOW_UNSAFE=1
    volumes:
      - type: bind
        source: airgap_model_manifest.yaml
        target: /airgap2/etc/nim/config/model_manifest.yaml
      - type: bind
        source: /home/jupyter/raid/llama3-8b-instruct_vhf
        target: /airgap/llama3-8b-instruct_vhf
